[build]
  publish = "."
  command = ""
  base = ""

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
